[project]
name = "dvc-data-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sjrom47", email = "sergiojimenezromero4@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dvc[s3]>=3.67.1",
]

[project.scripts]
dvc-data-pipeline = "dvc_data_pipeline:main"

[build-system]
requires = ["uv_build>=0.12.14,<0.13.0"]
build-backend = "uv_build"
